### PR TITLE
parse *ast.IndexExpr for generics

### PR DESCRIPTION
**Pull request by afmahmuda**

### CODE REVIEW

**Comment by afmahmuda** [comment]
solve https://github.com/bykof/go-plantuml/issues/17

**Comment by afmahmuda** [comment]
upgrade to go 1.19

**Comment by bykof** [comment]
Thank you very much for you pull request! 
I updated the test strategy to not use go 1.17 anymore. This is going to be a breaking change for this library, which will be reflected in the version. 

Could you pull newest commit on master and let the tests pass?

**Comment by afmahmuda** [comment]
sure, can do!

**Comment by bykof** [comment]
@afmahmuda  thank you very much for this contribution! Without you this project couldn't become better!

**Pull request merged**
